import type { Product } from "./types";

/**
 * Catálogo mock para la Etapa 1 (sin backend todavía).
 * En la Etapa 2 esto se reemplaza por la Store API de Medusa.
 */
export const PRODUCTS: Product[] = [
  // ------- RUNNING -------
  {
    id: "run-01",
    slug: "nike-vaporfly-3",
    name: "Vaporfly 3 Carbon",
    brand: "Nike",
    sport: "running",
    gender: "unisex",
    price: 899,
    compareAtPrice: 1099,
    rating: 4.9,
    reviews: 214,
    stock: 12,
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    colors: ["Volt", "Negro", "Blanco"],
    badge: "Top ventas",
    accent: "#B8FF32",
    featured: true,
  },
  {
    id: "run-02",
    slug: "hoka-mach-x",
    name: "Mach X Speed",
    brand: "HOKA",
    sport: "running",
    gender: "hombre",
    price: 649,
    rating: 4.7,
    reviews: 132,
    stock: 20,
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["Cyan", "Negro"],
    badge: "Nuevo",
    accent: "#38D9C7",
    featured: true,
  },
  {
    id: "run-03",
    slug: "saucony-endorphin-pro",
    name: "Endorphin Pro 4",
    brand: "Saucony",
    sport: "running",
    gender: "mujer",
    price: 720,
    compareAtPrice: 850,
    rating: 4.8,
    reviews: 98,
    stock: 8,
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Coral", "Negro"],
    accent: "#FF7A45",
  },
  {
    id: "run-04",
    slug: "adidas-adizero-adios-pro",
    name: "Adizero Adios Pro 3",
    brand: "Adidas",
    sport: "running",
    gender: "unisex",
    price: 780,
    rating: 4.6,
    reviews: 156,
    stock: 0,
    sizes: ["39", "40", "41", "42", "43"],
    colors: ["Blanco", "Rojo"],
    accent: "#F7F7F5",
  },

  // ------- NATACIÓN -------
  {
    id: "swim-01",
    slug: "arena-carbon-glide",
    name: "Powerskin Carbon Glide",
    brand: "Arena",
    sport: "natacion",
    gender: "hombre",
    price: 1290,
    compareAtPrice: 1490,
    rating: 4.9,
    reviews: 74,
    stock: 6,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro/Volt", "Azul"],
    badge: "Competición",
    accent: "#38D9C7",
    featured: true,
  },
  {
    id: "swim-02",
    slug: "speedo-fastskin-goggles",
    name: "Fastskin Pure Focus",
    brand: "Speedo",
    sport: "natacion",
    gender: "unisex",
    price: 210,
    rating: 4.7,
    reviews: 189,
    stock: 34,
    sizes: ["Única"],
    colors: ["Ahumado", "Espejo"],
    badge: "Top ventas",
    accent: "#5C7CFA",
    featured: true,
  },
  {
    id: "swim-03",
    slug: "arena-cobra-ultra",
    name: "Cobra Ultra Swipe",
    brand: "Arena",
    sport: "natacion",
    gender: "unisex",
    price: 245,
    compareAtPrice: 299,
    rating: 4.8,
    reviews: 121,
    stock: 18,
    sizes: ["Única"],
    colors: ["Espejo Volt", "Negro"],
    accent: "#B8FF32",
  },
  {
    id: "swim-04",
    slug: "finis-tempo-trainer",
    name: "Tempo Trainer Pro",
    brand: "FINIS",
    sport: "natacion",
    gender: "unisex",
    price: 165,
    rating: 4.6,
    reviews: 63,
    stock: 22,
    sizes: ["Única"],
    colors: ["Amarillo"],
    accent: "#FFD43B",
  },

  // ------- TRIATLÓN -------
  {
    id: "tri-01",
    slug: "hoka-tri-suit",
    name: "Aero Tri Suit Elite",
    brand: "HUUB",
    sport: "triatlon",
    gender: "hombre",
    price: 890,
    compareAtPrice: 1050,
    rating: 4.7,
    reviews: 41,
    stock: 9,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro/Volt"],
    badge: "Nuevo",
    accent: "#FF7A45",
  },
  {
    id: "tri-02",
    slug: "orca-wetsuit-openwater",
    name: "Wetsuit Open Water 3.8",
    brand: "Orca",
    sport: "triatlon",
    gender: "unisex",
    price: 1590,
    rating: 4.8,
    reviews: 52,
    stock: 5,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro"],
    accent: "#5C7CFA",
  },

  // ------- CICLISMO -------
  {
    id: "bike-01",
    slug: "specialized-helmet-evade",
    name: "Casco Evade 3 Aero",
    brand: "Specialized",
    sport: "ciclismo",
    gender: "unisex",
    price: 1150,
    compareAtPrice: 1350,
    rating: 4.8,
    reviews: 88,
    stock: 14,
    sizes: ["S", "M", "L"],
    colors: ["Negro", "Blanco"],
    badge: "Aero",
    accent: "#5C7CFA",
  },
  {
    id: "bike-02",
    slug: "assos-mille-bib",
    name: "Mille GT Bib Shorts",
    brand: "Assos",
    sport: "ciclismo",
    gender: "hombre",
    price: 640,
    rating: 4.7,
    reviews: 67,
    stock: 16,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro"],
    accent: "#A7ADB2",
  },

  // ------- NUTRICIÓN -------
  {
    id: "nut-01",
    slug: "maurten-gel-100",
    name: "Gel 100 (caja x12)",
    brand: "Maurten",
    sport: "nutricion",
    gender: "unisex",
    price: 380,
    compareAtPrice: 420,
    rating: 4.9,
    reviews: 301,
    stock: 60,
    sizes: ["Caja x12"],
    colors: ["Neutro"],
    badge: "Top ventas",
    accent: "#FFD43B",
    featured: true,
  },
  {
    id: "nut-02",
    slug: "sis-beta-fuel",
    name: "Beta Fuel 80 (x15)",
    brand: "SiS",
    sport: "nutricion",
    gender: "unisex",
    price: 320,
    rating: 4.6,
    reviews: 142,
    stock: 40,
    sizes: ["Caja x15"],
    colors: ["Naranja", "Limón"],
    accent: "#FF7A45",
  },

  // ------- TECNOLOGÍA / WEARABLES -------
  {
    id: "tech-01",
    slug: "garmin-forerunner-965",
    name: "Forerunner 965 AMOLED",
    brand: "Garmin",
    sport: "tecnologia",
    gender: "unisex",
    price: 2490,
    compareAtPrice: 2790,
    rating: 4.9,
    reviews: 176,
    stock: 7,
    sizes: ["47 mm"],
    colors: ["Negro/Volt", "Blanco"],
    badge: "GPS Multibanda",
    accent: "#B8FF32",
    featured: true,
  },
  {
    id: "tech-02",
    slug: "wahoo-tickr-hr",
    name: "TICKR Monitor Cardíaco",
    brand: "Wahoo",
    sport: "tecnologia",
    gender: "unisex",
    price: 290,
    rating: 4.7,
    reviews: 210,
    stock: 25,
    sizes: ["Única"],
    colors: ["Negro"],
    accent: "#FF6B6B",
  },

  // ------- ACCESORIOS -------
  {
    id: "acc-01",
    slug: "flipbelt-classic",
    name: "Cinturón de Running FlipBelt",
    brand: "FlipBelt",
    sport: "accesorios",
    gender: "unisex",
    price: 145,
    rating: 4.6,
    reviews: 98,
    stock: 50,
    sizes: ["S", "M", "L"],
    colors: ["Negro", "Volt"],
    accent: "#B8FF32",
  },

  // ------- RECUPERACIÓN -------
  {
    id: "rec-01",
    slug: "theragun-mini",
    name: "Theragun Mini Percusión",
    brand: "Therabody",
    sport: "recuperacion",
    gender: "unisex",
    price: 890,
    compareAtPrice: 990,
    rating: 4.8,
    reviews: 134,
    stock: 11,
    sizes: ["Única"],
    colors: ["Negro"],
    badge: "Recovery",
    accent: "#DA77F2",
  },
];

export function getFeatured(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}
